# Generated by Django 5.0.7 on 2024-08-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999999),
        ),
    ]
